name: Generate Release Notes

on:
  pull_request:
    types: [closed]

jobs:
  release-notes:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Release Notes using Bash Script
        env:
          GIT_TOKEN: ${{ secrets.GIT_AUTH_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: bash .github/scripts/generate_release_notes.sh

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add RELEASE_NOTES.md
          git commit -m "Update release notes for PR #${{ github.event.pull_request.number }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GIT_AUTH_TOKEN }}@github.com/Aswin-Sanjith/FuturePlanet.git HEAD:main
